### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by eliransapir** [rusq/osx-callhistory-decryptor#10] opened 2021-08-16 18:52 UTC
I'm getting this error:

sql: Scan error on column index 0, name "ZDATE": converting driver.Value type time.Time ("1990-07-23 01:31:02 +0000 UTC") to a float64: invalid syntax

The script runs and exports until it hits this row and then terminates without skipping or continuing.

**Comment by rusq** [comment] 2021-09-01 05:19
@eliransapir it looks like the date in your database in some funky format, I'm unable to reproduce with my history.  Do you mind sharing the file ` CallHistory.storedata` with me?

Drop it over here if so: https://www.dropbox.com/request/02OI8zhYOoUOlyerDlek

**Comment by eliransapir** [comment] 2021-09-01 17:00
my brother was able to fix his fix is available here: https://github.com/hensapir/osx-callhistory-decryptor

**Comment by rusq** [comment] 2021-09-02 01:20
@eliransapir that's great! Would he mind submitting a PR for the change to be merged?

**Closed as completed** 2021-09-20 12:33 UTC
Labels: bug
